#!/usr/bin/env bash

################################################################################
# Server configuration and startup
################################################################################


################################################################################
# Create EULA
################################################################################

create_eula() {

    local output="$1"


    if [[ -f "$output/eula.txt" ]]; then
        return
    fi


    cat > "$output/eula.txt" <<EOF
# Minecraft EULA
# Generated by Create+ Server Builder

eula=true
EOF

}


################################################################################
# Create server.properties
################################################################################

create_server_properties() {

    local output="$1"


    if [[ -f "$output/server.properties" ]]; then
        return
    fi


    cat > "$output/server.properties" <<EOF
# Create+ 6 NeoForge Server

motd=Create+ 6 Server

gamemode=survival
difficulty=normal

level-name=world

max-players=10

online-mode=true

allow-nether=true

spawn-monsters=true

enable-command-block=false

enable-rcon=false
enable-query=false

view-distance=10
simulation-distance=8

EOF

}


################################################################################
# Copy overrides
################################################################################

copy_overrides() {

    local workdir="$1"
    local output="$2"


    if [[ ! -d "$workdir/overrides" ]]; then
        return
    fi


    cp \
        -a \
        "$workdir/overrides/." \
        "$output/"

}


################################################################################
# Find NeoForge arguments
################################################################################

find_neoforge_args() {

    local output="$1"


    find \
        "$output/libraries" \
        -name unix_args.txt \
        -type f \
        | head -n 1

}


################################################################################
# Create run script
################################################################################

create_run_script() {

    local output="$1"

    local java_bin="${SERVER_JAVA:-java}"

    if [[ -z "$java_bin" ]]; then
        java_bin=$(find_java 2>/dev/null || true)
    fi

    if [[ -z "$java_bin" ]]; then
        java_bin="java"
    fi

    local args_file
    args_file=$(find_neoforge_args "$output")

    local relative_args_file=""
    if [[ -n "$args_file" ]]; then
        relative_args_file="${args_file#"$output"/}"
    fi

    cat > "$output/run.sh" <<EOF
#!/usr/bin/env sh
set -eu

JAVA_BIN="\${JAVA_BIN:-$java_bin}"
if [ -z "\$JAVA_BIN" ]; then
    JAVA_BIN=java
fi

exec "\$JAVA_BIN" @user_jvm_args.txt @"$relative_args_file" "\$@"
EOF

    chmod +x "$output/run.sh"

}


################################################################################
# Create start script
################################################################################

create_start_script() {

    local output="$1"

    local java_bin="${SERVER_JAVA:-java}"

    if [[ -z "$java_bin" ]]; then
        java_bin=$(find_java 2>/dev/null || true)
    fi

    if [[ -z "$java_bin" ]]; then
        java_bin="java"
    fi

    cat > "$output/start.sh" <<EOF
#!/usr/bin/env bash

set -euo pipefail


cd "\$(dirname "\$0")"


RAM="\${RAM:-8G}"


################################################################################
# Java detection
################################################################################

JAVA_BIN="\${JAVA_BIN:-$java_bin}"


echo
echo "Starting Create+ 6 NeoForge server"
echo "Java:"
"\$JAVA_BIN" -version
echo
echo "RAM: \$RAM"
echo


################################################################################
# Prefer NeoForge generated launcher
################################################################################

if [[ -x "./run.sh" ]]
then

    export JAVA_BIN
    exec ./run.sh

fi


################################################################################
# Fallback launcher
################################################################################

ARGS_FILE=$(find libraries \
    -name unix_args.txt \
    -type f \
    | head -n 1)


if [[ -z "\$ARGS_FILE" ]]
then

    echo "ERROR: NeoForge unix_args.txt not found."
    exit 1

fi


exec "\$JAVA_BIN" \
    -Xms2G \
    -Xmx"\$RAM" \
    @"\$ARGS_FILE" \
    nogui
EOF


    chmod +x "$output/start.sh"

}


################################################################################
# Create stop helper
################################################################################

create_stop_script() {

    local output="$1"


    cat > "$output/stop.sh" <<'EOF'
#!/usr/bin/env bash

echo "Use the Minecraft server console command:"
echo
echo "stop"
echo
echo "for a safe shutdown."
EOF


    chmod +x "$output/stop.sh"

}


################################################################################
# Prepare server
################################################################################

prepare_server() {

    local output="$1"


    create_eula \
        "$output"


    create_server_properties \
        "$output"


    create_run_script \
        "$output"


    create_start_script \
        "$output"


    create_stop_script \
        "$output"

}